# WebServer
server:
  port: 8080

# Service Information
service:
  name: @project.name@
  description: @project.description@
  version: @project.version@

# Logging
logging:
  level:
    root: INFO
    service: TRACE

# Outgoing Services
