# WebServer
server:
  port: 8080

# Service Information
service:
  name: @project.name@
  description: @project.description@
  version: @project.version@

# Swagger
springfox:
  documentatation:
    swagger:
      v2:
        path: /api-docs
